### ISSUE TITLE
[BUG] Bot replies to invalid commands

### ISSUE THREAD

**Issue by qawery-just-sad** [qawery-just-sad/Discord-csgosurf-bot#2]
**1. Bot replies to commands like !!, !afdafdfef ...** 
**2. ![image](https://user-images.githubusercontent.com/53490397/69493032-18b58580-0eaa-11ea-86e1-80cad6450cb4.png)**
_**3, Help - qawery**_

**Comment by qawery-just-sad** [comment]
fixed with commit e19aea3

**Comment by qawery-just-sad** [comment]
aliases deleted due to fixing issue

**Comment by 13ace37** [comment]
https://github.com/totles/z4lab-discord-bot/blob/master/util/alias.js
